cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3225806
  brandStrength: 0.8353068241849542
  lightness: 0.3010753
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 0.5913978
typography_spectrum: 0.6200717
layout_spectrum: 0.9713262
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Wily Creative
